services:
  backend:
    build: ./
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - ktor-network
    depends_on:
      - postgres
    environment:
      DATABASE_NAME: jdbc:postgresql://postgres:5432/flashcards?currentSchema=info
      DATABASE_PASSWORD: adminadmin
      DATABASE_USER: postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_ROOT_PASSWORD: adminadmin
    ports:
      - "5432:5432"
    networks:
      - ktor-network
    expose:
      - 5432

networks:
  ktor-network:
    driver: bridge